# Generated by Django 3.2.7 on 2021-09-06 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='for_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sectiondata', to=settings.AUTH_USER_MODEL),
        ),
    ]
